# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rsi_status_bluesky:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5.3.0
      #   with:
      #     python-version: '3.13'
      # - run: pip install google-generativeai
      # Runs a single command using the runners shell
      - name: Fetch Post Data
              # important, add an id to your step
        id: rss
        uses: CodingBull-dev/newest-rss-post-action@main
        with:
          # make sure that the link is an RSS site
          rss: "https://status.robertsspaceindustries.com/index.xml"
      - name: Make Gemini cook a sentence
        id: gemini
        # shell: python
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
            echo "GEMINI_SENTENCE=$(curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}" -H 'Content-Type: application/json' -X POST -d '{ "contents": [{ "parts":[{"text": "Fais une phrase en francais à propos du status ${{ steps.rss.outputs.title }} qui est affiché ici. Cette phrase doit parler de l'etat des serveurs Star Citizen"}]}]}')" >> $GITHUB_ENV
      # Runs a set of commands using the runners shell
      - name: Send Bluesky Post
        uses: myConsciousness/bluesky-post@v5
        with:
          identifier: ${{ secrets.BLUESKY_HANDLE }} # Your handle (example: username.bsky.social)
          password: ${{ secrets.BLUESKY_PASSWORD }} # Your password
          labels: "starcitizen,rsistatus"
          tags: "starcitizen,rsistatus,rsi"
          link-preview-url: "${{ steps.rss.outputs.url }}"
          text: |
            ${{ env.GEMINI_SENTENCE }} #StarCitizen
            Status : ${{ steps.rss.outputs.title }}
            [Créez votre compte StarCitizen](https://shorturl.at/ItWLR)
